### This code helps us do a common data processing required for all the models created using consumer and platform data

#### importing required libraries

In [20]:
import os
import sys
import math
import sklearn
import scipy
import pandas as pd
import import_ipynb
sys.path.append(os.path.abspath(os.path.join('__file__','../../')))
from config.configs import interaction_weightages
from sklearn.model_selection import train_test_split

# setting up below conf helps broaden the display of pandas dataframes

# pd.set_option('display.max_columns', None)  
# pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)

#### module that reads both the data sources available for creating recommendations

In [21]:
def reading_content_data():
    
    plat_articles = pd.read_csv(r'C:\Users\SumitJain\Documents\upgd\recommendation_system\data\platform_content.csv')
    plat_articles = plat_articles[plat_articles['interaction_type'] == 'content_present']
#   or alternatively can be done using
#   df_pres = plat_articles.interaction_type.str.contains('content_present', case=False)
#   plat_articles = plat_articles[df_pres]

    user_behaviour_df = pd.read_csv(r'C:\Users\SumitJain\Documents\upgd\recommendation_system\data\consumer_transanctions.csv')

    return plat_articles,user_behaviour_df

plat_articles,user_behaviour_df = reading_content_data()

plat_articles.shape
plat_articles.head(2)

,event_timestamp,interaction_type,item_id,producer_id,producer_session_id,producer_device_info,producer_location,producer_country,item_type,item_url,title,text_description,language
1,1459193988,content_present,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
2,1459194146,content_present,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en

In [22]:
user_behaviour_df.head(3)
# user_behaviour_df.shape

,event_timestamp,interaction_type,item_id,consumer_id,consumer_session_id,consumer_device_info,consumer_location,country
0,1465413032,content_watched,-3499919498720038879,-8845298781299428018,1264196770339959068,NaN,NaN,NaN
1,1465412560,content_watched,8890720798209849691,-1032019229384696495,3621737643587579081,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,NY,US
2,1465416190,content_watched,310515487419366995,-1130272294246983140,2631864456530402479,NaN,NaN,NaN

#### Merging consumer and platform content metadata to come up with a common dataset containing all attributes.

In [23]:
merged_inner = pd.merge(left=plat_articles, right=user_behaviour_df, left_on='item_id', right_on='item_id')

# size of the output data

merged_inner.shape
merged_inner.head(3)

,event_timestamp_x,interaction_type_x,item_id,producer_id,producer_session_id,producer_device_info,producer_location,producer_country,item_type,item_url,title,text_description,language,event_timestamp_y,interaction_type_y,consumer_id,consumer_session_id,consumer_device_info,consumer_location,country
0,1459193988,content_present,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en,1459270471,content_watched,2873028073541627603,-3228450896145227905,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,SP,BR
1,1459194146,content_present,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en,1459539433,content_watched,8414731042150985013,4543899740167763020,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4...,MG,BR
2,1459194474,content_present,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en,1459476271,content_watched,-7267769888748948232,-1350132153769633851,Android - Native Mobile App,MG,BR

#### getting interaction_weightages from configs and applying on each interaction type to get type weightages

In [24]:
user_behaviour_df['type_weightage'] = user_behaviour_df['interaction_type'].apply(lambda x: interaction_weightages[x])

In [25]:
user_behaviour_df

,event_timestamp,interaction_type,item_id,consumer_id,consumer_session_id,consumer_device_info,consumer_location,country,type_weightage
0,1465413032,content_watched,-3499919498720038879,-8845298781299428018,1264196770339959068,NaN,NaN,NaN,1.0
1,1465412560,content_watched,8890720798209849691,-1032019229384696495,3621737643587579081,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,NY,US,1.0
2,1465416190,content_watched,310515487419366995,-1130272294246983140,2631864456530402479,NaN,NaN,NaN,1.0
3,1465413895,content_followed,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN,4.0
4,1465412290,content_watched,-7820640624231356730,-445337111692715325,561148 1178424124714,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...
72307,1485190425,content_liked,-6590819806697898649,-9016528795238256703,8614469745607949425,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4...,MG,BR,2.0
72308,1485190425,content_watched,-5813211845057621660,102305705598210278,5527770709392883642,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR,1.0
72309,1485190072,content_watched,-1999468346928419252,-9196668942822132778,-8300596454915870873,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR,1.0
72310,1485190434,content_watched,-6590819806697898649,-9016528795238256703,8614469745607949425,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4...,MG,BR,1.0
72311,1485187988,content_watched,5669290109546991426,5713241217519616260,6704552481483665372,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,MG,BR,1.0

#### getting content consumed by each users as well as getting users with more than 5 items to understand if there are enough 
#### users with good enough engagement as evident below

In [26]:
consumer_behaviour_count_df = user_behaviour_df.groupby(['consumer_id', 'item_id']).size().groupby('consumer_id').size()
consumer_behaviour_count_df


print('no. of users: %d' % len(consumer_behaviour_count_df))
users_with_enough_user_behaviour_df = consumer_behaviour_count_df[consumer_behaviour_count_df >= 5].reset_index()[['consumer_id']]
print('no. of users with atleast 5 consumptions: %d' % len(users_with_enough_user_behaviour_df))

no. of users: 1895
no. of users with atleast 5 consumptions: 1140

#### getting only those interactions which has >5 items consumed by users for better model performance in future

In [27]:
print('no. of interactions: %d' % len(user_behaviour_df))
user_behaviour_from_selected_users_df = user_behaviour_df.merge(users_with_enough_user_behaviour_df, how = 'right',left_on = 'consumer_id',
right_on = 'consumer_id')
print('no. of interactions from users with at least 5 engagement: %d' % len(user_behaviour_from_selected_users_df))

no. of interactions: 72312
no. of interactions from users with at least 5 engagement: 69868

In [29]:
user_behaviour_full_df = user_behaviour_from_selected_users_df[['consumer_id', 'item_id','type_weightage']]
user_behaviour_full_df.to_csv(r'C:\Users\SumitJain\Documents\upgd\recommendation_system\data\data_rating.csv')

#### normalizing users event types

In [30]:
user_behaviour_full_df = user_behaviour_from_selected_users_df.groupby(['consumer_id', 'item_id'])['type_weightage'].sum() \
.apply(lambda x: math.log(1+x, 2)).reset_index() # lambda x: math.log(1+x, 2)
print('no. of unique user/item interactions: %d' % len(user_behaviour_full_df))
user_behaviour_full_df.head(10)
# user_behaviour_full_df.to_csv("data.csv")

no. of unique user/item interactions: 39106

           consumer_id              item_id  type_weightage
0 -9223121837663643404 -8949113594875411859        1.000000
1 -9223121837663643404 -8377626164558006982        1.000000
2 -9223121837663643404 -8208801367848627943        1.000000
3 -9223121837663643404 -8187220755213888616        1.000000
4 -9223121837663643404 -7423191370472335463        3.169925
5 -9223121837663643404 -7331393944609614247        1.000000
6 -9223121837663643404 -6872546942144599345        1.000000
7 -9223121837663643404 -6728844082024523434        1.000000
8 -9223121837663643404 -6590819806697898649        1.000000
9 -9223121837663643404 -6558712014192834002        1.584963

#### Get the user's data and merge in the content info for modelling usage

In [31]:
def get_users_content_data(person_id, user_behaviour_df):
    interacted_items = user_behaviour_df.loc[person_id]['item_id']
    return set(interacted_items if type(interacted_items) == pd.Series else [interacted_items])

#### spliting to train test data

In [32]:
def train_test_user_behaviour():
    user_behaviour_train_df, user_behaviour_test_df = train_test_split(user_behaviour_full_df,test_size=0.15,random_state=22)
    # stratify=user_behaviour_full_df['consumer_id'], 
    print('engagement in train set: %d' % len(user_behaviour_train_df))
    print('engagement in on test set: %d' % len(user_behaviour_test_df))
    
    return user_behaviour_train_df, user_behaviour_test_df

#Indexing by consumer_id to speed up the searches during evaluation
user_behaviour_train_df, user_behaviour_test_df = train_test_user_behaviour()
print(user_behaviour_train_df)

engagement in train set: 33240
engagement in on test set: 5866
               consumer_id              item_id  type_weightage
2103  -8550167523008133722  -454649054276160610        1.000000
31618  4670267857749552625  6587635730509289343        1.000000
18745  -444330148331768170 -1297580205670251233        2.000000
34490  6686431125336194142 -4994468824009200256        1.000000
27398  3576137684812235192 -5570129644089964821        1.000000
...                    ...                  ...             ...
20971   692689608292948411  2435024834845042614        2.321928
23030  1623838599684589103 -5781461435447152359        1.000000
24932  2416280733544962613  7400903238402587728        1.584963
31680  4778050608932092852  1642787330067525131        2.000000
29484  3829784524040647339  7273139206342584600        1.000000

[33240 rows x 3 columns]

#### getting_user_behaviour_indexed for modelling usage

In [33]:
def getting_user_behaviour_indexed():
    
    user_behaviour_full_indexed_df = user_behaviour_full_df.set_index('consumer_id')
    user_behaviour_train_indexed_df = user_behaviour_train_df.set_index('consumer_id')
    user_behaviour_test_indexed_df = user_behaviour_test_df.set_index('consumer_id')
#     print(user_behaviour_train_indexed_df)
    return user_behaviour_full_indexed_df,user_behaviour_train_indexed_df,user_behaviour_test_indexed_df

getting_user_behaviour_indexed()

(                                  item_id  type_weightage
 consumer_id
 -9223121837663643404 -8949113594875411859        1.000000
 -9223121837663643404 -8377626164558006982        1.000000
 -9223121837663643404 -8208801367848627943        1.000000
 -9223121837663643404 -8187220755213888616        1.000000
 -9223121837663643404 -7423191370472335463        3.169925
 ...                                   ...             ...
  9210530975708218054  8477804012624580461        3.459432
  9210530975708218054  8526042588044002101        1.000000
  9210530975708218054  8856169137131817223        1.000000
  9210530975708218054  8869347744613364434        1.000000
  9210530975708218054  9209886322932807692        1.000000

 [39106 rows x 2 columns],
                                   item_id  type_weightage
 consumer_id
 -8550167523008133722  -454649054276160610        1.000000
  4670267857749552625  6587635730509289343        1.000000
 -444330148331768170  -1297580205670251233        2.000000
  6686431125336194142 -4994468824009200256        1.000000
  3576137684812235192 -5570129644089964821        1.000000
 ...                                   ...             ...
  692689608292948411   2435024834845042614        2.321928
  1623838599684589103 -5781461435447152359        1.000000
  2416280733544962613  7400903238402587728        1.584963
  4778050608932092852  1642787330067525131        2.000000
  3829784524040647339  7273139206342584600        1.000000

 [33240 rows x 2 columns],
                                   item_id  type_weightage
 consumer_id
 -3954277405987282296 -4029704725707465084        1.000000
  6196511437047227700 -4145260601063545880        2.321928
 -4384580909851654688 -3275688295651945765        1.584963
  8676130229735483748   909703879562824170        2.000000
 -2901997243166418276  7217636150008996485        1.000000
 ...                                   ...             ...
  8941502917401491878 -5750828394349042089        1.000000
 -6850499260033618177 -5636731245639685654        1.000000
 -3596626804281480007  1440793148901830221        1.584963
 -510621402112686165   7459643459148487877        1.000000
  8652251853329201030  6817244649248188271        1.000000

 [5866 rows x 2 columns])